version: build{build}
image: Visual Studio 2017
services: mssql2017
branches:
  only:
    - master
    - develop
environment:
  SqlServer/MasterConnectionString: Server=(local)\SQL2017;Database=master;User ID=sa;Password=Password12!
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
